- src/entry_points/glossary.md
Add a definition in the glossary for the term "PETs".
> Add definition for PETs

- src/overview/overview.md
This is an update of the introduction paragraph from the `overview` page, based on @mattthieu comments. Looks good to me! What do you think about it?
> Update overview introduction with Substra key features

- Makefile
- README.md
- conf.py
- requirements.txt
This adds a new make target: livehtml 
It helps a great deal when writing doc and testing the end result.
> Add sphinx-autobuild

- Makefile
- conf.py
- src/index.rst
This makes sure all doc contents are in `src/ `.
> Move index to src folder

- Makefile
Add `echo "doc.substra.ai" > docs/CNAME` to make file.
> Update make to add CNAME file to docs

- Makefile
Add `*` to cp command `cp -R _build/html/* docs/`
> Fix Makefile cp command

- docs/_sources/getting_started/installation/local_install_skaffold.md.txt
- docs/getting_started/installation/local_install_skaffold.html
- src/getting_started/installation/local_install_skaffold.md
> Update Skaffold Version

- docs/_sources/getting_started/installation/local_install_skaffold.md.txt
- docs/getting_started/installation/local_install_skaffold.html
- src/getting_started/installation/local_install_skaffold.md
> Fix venv urls

- docs/_sources/overview/overview.md.txt
- docs/overview/overview.html
- src/overview/overview.md
> Fix links in overview section

- docs/_sources/index.rst.txt
- docs/index.html
- src/index.rst
> Add slack badge on the documentation home

- docs/_sources/getting_started/installation/local_install_skaffold.md.txt
- docs/getting_started/installation/local_install_skaffold.html
- src/getting_started/installation/local_install_skaffold.md
> Update cli commands

- docs/_sources/setup/local_install_skaffold.md.txt
- docs/setup/local_install_skaffold.html
- src/setup/local_install_skaffold.md
> Update k8s version

- README.md
> Update commit msg & project tree

- docs/_sources/cheatsheet_cli.md.txt
- docs/_static/pygments.css
- docs/cheatsheet_cli.html
- src/cheatsheet_cli.md
> Fix broken link in cheatsheet cli

- docs/CONTRIBUTING.html
- docs/architecture.html
- docs/cheatsheet_cli.html
- docs/concepts.html
- docs/debugging.html
- docs/demo.html
- docs/errors.html
- docs/faq.html
- docs/genindex.html
- docs/glossary.html
- docs/index.html
- docs/overview.html
- docs/permissions.html
- docs/publish.html
- docs/search.html
- docs/setup/cheatsheet_vm.html
- docs/setup/further_resources.html
- docs/setup/index.html
- docs/setup/local_install_skaffold.html
- docs/usage.html
- requirements.txt
Fixed the docutils version in docs requirement to prevent style from breaking
> Set docutils version in docs requirements

- docs/source/documentation/concepts.rst
- docs/source/substrafl_doc/index.rst
- docs/source/substrafl_doc/substrafl_overview.rst
> docs: add substrafl overview

- docs/source/operations/deploy.rst
Reference the chart repository and chart documentation.
> docs: link to helm repo

- CHANGELOG.md
- docs/source/additional/release.rst
- docs/source/conf.py
- docs/source/index.rst
- examples/titanic_example/assets/algo_random_forest/predict/Dockerfile
- examples/titanic_example/assets/algo_random_forest/train/Dockerfile
- examples/titanic_example/assets/metric/Dockerfile
- substrafl_examples/strategies_examples/assets/metric/Dockerfile
TODO: check the hlf-k8s infos when released
> chore: release 0.21.0-rc1

- CHANGELOG.md
- docs/source/conf.py
- docs/source/substrafl_doc/substrafl_overview.rst
Remove ugly button "download all examples"
> docs: Remove download all examples button.

- docs/source/conf.py
- docs/source/documentation/debug.rst
- examples/titanic_example/assets/algo_random_forest/titanic_algo_rf.py
- examples/titanic_example/assets/dataset/description.md
- examples/titanic_example/assets/dataset/titanic_opener.py
- examples/titanic_example/assets/metric/titanic_metrics.py
- substrafl_examples/strategies_examples/assets/dataset/description.md
- substrafl_examples/strategies_examples/assets/dataset/opener.py
- substrafl_examples/strategies_examples/assets/metric/metrics.py
- substrafl_examples/strategies_examples/plot_substrafl_fedavg.py
Use `datasamples` as input identifiers for X and y accros all functions. 
Pass `rank` within a new argument named `task_properties`
Companion PRs: 
- substra: https://github.com/Substra/substra/pull/284
- substrafl: https://github.com/Substra/substrafl/pull/20
- substra-tests: https://github.com/Substra/substra-tests/pull/207
- substra-tools (main) https://github.com/Substra/substra-tools/pull/58
- substra-documentation:  (here)  https://github.com/Substra/substra-documentation/pull/179
> feat: uniformize inputs and outputs for all algos

- CHANGELOG.md
- examples/titanic_example/assets/metric/titanic_metrics.py
- substrafl_examples/strategies_examples/assets/metric/metrics.py
Main PR:
- https://github.com/Substra/substra-tools/pull/60
> feat: update the example metrics

- examples/titanic_example/plot_titanic.py
- substrafl_examples/strategies_examples/plot_substrafl_fedavg.py
Signed-off-by: Fabien Gelus <fabien.gelus@owkin.com>
Substrafl example not working in docker mode -> tested
Substra example not working in remote mode -> not tested by me 
build tested locally
> fix: examples

- CHANGELOG.md
- docs/source/additional/release.rst
- docs/source/conf.py
- docs/source/index.rst
- examples/titanic_example/assets/algo_random_forest/predict/Dockerfile
- examples/titanic_example/assets/algo_random_forest/train/Dockerfile
- examples/titanic_example/assets/metric/Dockerfile
- examples/titanic_example/plot_titanic.py
- substrafl_examples/strategies_examples/assets/metric/Dockerfile
- substrafl_examples/strategies_examples/plot_substrafl_fedavg.py
examples tested in subprocess / docker
> chore: release 0.21.0

- docs/source/operations/howto/backend-deployment.rst
Some minor fixes after a review from @AurelienGasser on #192.
> docs: fix backend deployment docs

- docs/source/index.rst
- docs/source/operations/getting-started.rst
- docs/source/operations/getting-started/k3-create.sh
This page will describe to new users how to locally deploy substra to ease the process of starting using substra stack.
> docs: Add getting started page

- CHANGELOG.md
- docs/source/documentation/debug.rst
- docs/source/documentation/get_performances.rst
- examples/titanic_example/plot_titanic.py
https://github.com/Substra/substra/pull/299
https://github.com/Substra/substrafl/pull/31
https://github.com/Substra/substra-tests/pull/221
> feat: use generic task

- docs/source/additional/community.rst
> docs: update slack URL

- CHANGELOG.md
- substrafl_examples/strategies_examples/plot_substrafl_fedavg.py
- substrafl_examples/strategies_examples/utils/mnist_data.py
Asana card: https://app.asana.com/0/1203124674173179/1203200116896579/f
> feat: refacto mnist

- CHANGELOG.md
- examples/titanic_example/assets/algo_random_forest/titanic_algo_rf.py
- examples/titanic_example/assets/metric/titanic_metrics.py
- substrafl_examples/strategies_examples/assets/metric/metrics.py
- substrafl_examples/strategies_examples/plot_substrafl_fedavg.py
- https://github.com/Substra/substra-tools/pull/65 (MAIN)
- https://github.com/Substra/substra/pull/310
- https://github.com/Substra/substrafl/pull/37
- https://github.com/Substra/substra-documentation/pull/202
- https://github.com/Substra/substra-tests/pull/225
> feat: register substratools function with decorator

- substrafl_examples/strategies_examples/assets/dataset/opener.py
- substrafl_examples/strategies_examples/assets/mnist_data.py
- substrafl_examples/strategies_examples/plot_substrafl_fedavg.py
Co-authored-by: ThibaultFy <ThibaultFy@users.noreply.github.com>
> chore: update mnist example

- CHANGELOG.md
- docs/source/documentation/concepts.rst
- docs/source/documentation/debug.rst
https://app.asana.com/0/1203124674173179/1203292057972037/f
> doc: update doc on tuples

- README.md
- docs/source/documentation/debug.rst
- docs/source/documentation/get_performances.rst
- docs/source/substrafl_doc/substrafl_overview.rst
- examples/titanic_example/plot_titanic.py
> chore: misc clean up

- docs/source/index.rst
- docs/source/substrafl_doc/substrafl_overview.rst
- substrafl_examples/strategies_examples/plot_substrafl_fedavg.py
> docs: improve english language

- docs/source/documentation/debug.rst
- docs/source/substrafl_doc/substrafl_overview.rst
> docs: windows trouble shoot on docker mode

- CHANGELOG.md
- docs/source/operations/howto/backend-deployment.rst
- docs/source/operations/howto/mtls-setup.rst
- docs/source/operations/howto/orchestrator-deployment.rst
Add a new page in the how-to section to describe how to set up mTLS
Signed-off-by: Guilhem Barthes <guilhem.barthes@owkin.com>
> docs: Add initial mTLS setup

- docs/source/conf.py
> chore: update component versions

- docs/source/additional/faq.rst
- docs/source/additional/release.rst
- docs/source/documentation/concepts.rst
- docs/source/documentation/debug.rst
- docs/source/substrafl_doc/substrafl_overview.rst
- examples/titanic_example/plot_titanic.py
- substrafl_examples/get_started/plot_substrafl_torch_fedavg.py
> docs: review of documentation

- examples/titanic_example/plot_titanic.py
- substrafl_examples/get_started/plot_substrafl_torch_fedavg.py
- substrafl_examples/go_further/plot_substrafl_sklearn_fedavg.py
> docs: put Binder forward at the start of the examples

- CHANGELOG.md
- docs/source/index.rst
- docs/source/operations/upgrade_notes.rst
Signed-off-by: Guilhem Barthes <guilhem.barthes@owkin.com>
> docs: app upgrade notes for Substra 0.23.0

- examples/titanic_example/plot_titanic.py
- substrafl_examples/get_started/plot_substrafl_torch_fedavg.py
Signed-off-by: EazyAl <ali.imran@owkin.com>
> docs: minor improvements

- examples/titanic_example/assets/algo_random_forest/titanic_algo_rf.py
- examples/titanic_example/assets/dataset/titanic_opener.py
- examples/titanic_example/plot_titanic.py
- remove useless category parameter in the AlgoSpec definition
- rename inputs and outputs
- move the most important function at the top of the algo and opener files
> docs: Titanic example clean up

- CHANGELOG.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Signed-off-by: Milouu <milan.roustan@owkin.com>
Add files for contributing guide & code of conduct redirecting to their respective page in the substra documentation.
> chore: Add files for contributing guide & code of conduct

- CHANGELOG.md
- examples/titanic_example/plot_titanic.py
- substrafl_examples/get_started/plot_substrafl_torch_fedavg.py
- substrafl_examples/go_further/plot_substrafl_sklearn_fedavg.py
- https://github.com/Substra/substra/pull/332 - MAIN
- https://github.com/Substra/substra-backend/pull/551
- https://github.com/Substra/substra-documentation/pull/246
- https://github.com/Substra/substrafl/pull/67
- https://github.com/Substra/substra-tests/pull/235
- https://github.com/Substra/orchestrator/pull/116
https://app.asana.com/0/1202209633046022/1203074394111393/f
> chore: remove test only from Datasamples

- docs/source/contributing/getting-started.rst
Hi,
First, thank you for developing Substra!
I am trying setting up the development environment given in the documentation but I have had problems when running `skaffold run`.
Those steps might be needed in order to resolve the charts for `substra/orchestrator` and `substra/substra-backend`.
cc @Fabien-GELUS, whom I mentioned this.
On a side note: I have opened this Pull Request without opening any issue before hand. I searched for contributing conventions and guidelines (usually given in the doc or in `CONTRIBUTING.{md,est}`) but haven't been able to. Do you have any, yet? Thank you!
Signed-off-by: Julien Jerphanion <git@jjerphan.xyz>
> docs: Mention updating Helm Charts for the first time configuration

- docs/source/additional/release.rst
> chore: update release changelog

- docs/source/substrafl_doc/substrafl_overview.rst
> docs: rephrase centralized strategy

- docs/source/contributing/local-deployment.rst
> docs: add how to launch computation on a local deployment

- CHANGELOG.md
- docs/source/operations/overview.rst
- docs/source/substrafl_doc/substrafl_overview.rst
Add the maintain and tested version (and degree of maintenance) for each OS and version of OS.
> doc: explain supported os

- CHANGELOG.md
- substrafl_examples/get_started/run_mnist_torch.py
- substrafl_examples/go_further/run_iris_sklearn.py
https://app.asana.com/0/1203124674173179/1203493303699138/f
https://github.com/Substra/substrafl/pull/85
> chore: apply changes on evaluation strategy

- substrafl_examples/go_further/run_iris_sklearn.py
- substrafl_examples/go_further/sklearn_fedavg_assets/requirements.txt
Signed-off-by: SdgJlbl <sarah.diot-girard@owkin.com>
> doc: minor changes in Iris sklearn example

- substrafl_examples/get_started/run_mnist_torch.py
- substrafl_examples/get_started/torch_fedavg_assets/dataset/description.md
- substrafl_examples/get_started/torch_fedavg_assets/dataset/mnist_dataset.py
- substrafl_examples/get_started/torch_fedavg_assets/requirements.txt
This PR can be reviewed commit by commit (and each commit can be reverted if necessary). 
Changes proposed: 
- fix typos
- change usages of `list()` for `[]` for [performance](https://stackoverflow.com/questions/5790860/and-vs-list-and-dict-which-is-better) and Pythonicity reasons
- use list comprehension for readability and Pythonicity reasons (can revert if no consensus)
- use pandas MultiIndex for improving readability of results (same)
> Update mnist example

- CHANGELOG.md
- docs/source/index.rst
> docs: update installation paragraph in landing page

- .github/workflows/build.yml
- CHANGELOG.md
- docs/source/additional/release.rst
- docs/source/additional/releases.yaml
- docs/source/conf.py
Signed-off-by: Guilhem Barthes <guilhem.barthes@owkin.com>
> chore: release 0.25.0

- CHANGELOG.md
- substrafl_examples/get_started/run_mnist_torch.py
- substrafl_examples/go_further/run_iris_sklearn.py
- https://github.com/Substra/substrafl/pull/98
> chore: algo as parameter of strategy

- docs/source/documentation/r_scripts.rst
- docs/source/documentation/user_guide.rst
- examples/titanic_example/README.rst
Based on this [POC](https://github.com/SdgJlbl/RinSubstra)
> feat: add an how-to guide to use R with Substra

- CHANGELOG.md
> chore: update changelog for 0.26.0

- CHANGELOG.md
- examples/titanic_example/run_titanic.py
- substrafl_examples/get_started/run_mnist_torch.py
- substrafl_examples/go_further/run_iris_sklearn.py
> docs: rename function names

- CHANGELOG.md
- README.md
- docs/source/contributing/local-deployment.rst
- examples/diabetes_example/run_diabetes.py
- examples/titanic_example/run_titanic.py
- substrafl_examples/get_started/run_mnist_torch.py
- substrafl_examples/go_further/run_iris_sklearn.py
And update documentation with the latest docstrings
> feat: use the new way of configuring Substra clients in tutorials

- CHANGELOG.md
- substrafl_examples/get_started/run_mnist_torch.py
- substrafl_examples/go_further/run_iris_sklearn.py
- https://github.com/Substra/substrafl/pull/117
> feat: update example with multiple performance in test data node

- CHANGELOG.md
- docs/source/documentation/client_configuration.rst
- docs/source/documentation/user_guide.rst
How-to guide following https://github.com/Substra/substra/pull/353
> feat: how to configure substra clients

- CHANGELOG.md
- substrafl_examples/go_further/run_iris_sklearn.py
Update the example with the changes implied by https://github.com/Substra/substrafl/pull/120
> chore: update Iris example with compute plan builder changes

- CHANGELOG.md
- substrafl_examples/get_started/run_mnist_torch.py
- substrafl_examples/go_further/run_iris_sklearn.py
- https://github.com/Substra/substrafl/pull/125
> chore: download utils in substrafl examples

- CHANGELOG.md
- docs/source/documentation/concepts.rst
> doc: improve permission page

- CHANGELOG.md
- docs/source/documentation/concepts.rst
- docs/source/substrafl_doc/substrafl_overview.rst
Add definition on rank, local and shared states
closes FL-988
> doc: add documentation on local and shared states

- CHANGELOG.md
- substrafl_examples/get_started/run_mnist_torch.py
- substrafl_examples/go_further/run_iris_sklearn.py
> docs: add experiment name in examples

- CHANGELOG.md
- docs/source/additional/release.rst
- docs/source/additional/releases.yaml
> chore: release 0.29.0

- CHANGELOG.md
- docs/source/conf.py
- examples/diabetes_example/run_diabetes.py
- examples/titanic_example/run_titanic.py
- substrafl_examples/get_started/run_mnist_torch.py
- substrafl_examples/go_further/run_diabetes_substrafl.py
- substrafl_examples/go_further/run_iris_sklearn.py
- substrafl_examples/go_further/run_mnist_cyclic.py
Temporarily deactivating Binder on documentation examples as it is not working as we intend right now, and we don't have the time to fix it right now.
> chore: deactivate binder

- CHANGELOG.md
- docs/source/documentation/components.rst
> docs: add link to python libraries in Components

- CHANGELOG.md
- docs/source/documentation/concepts.rst
> doc: add user management paragraph

- CHANGELOG.md
- docs/source/documentation/backend/index.rst
- docs/source/documentation/components.rst
- docs/source/documentation/frontend/index.rst
- docs/source/documentation/orchestrator/index.rst
Add some documentation for the frontend component in the components section.
Fixes FL-1138
> feat: Add frontend documentation to components

- CHANGELOG.md
- docs/source/additional/release.rst
- docs/source/additional/releases.yaml
https://owkin-substra-documentation--373.com.readthedocs.build/en/373/additional/release.html
> chore: release 0.33.1

- CHANGELOG.md
- docs/source/additional/release.rst
- docs/source/additional/releases.yaml
- docs/source/how-to/deploying-substra/upgrade-notes.rst
> chore: release 0.34.0

- docs/source/how-to/developing-substra/local-deployment.rst
- `${PWD}` with `$PWD` to make it compatible also with [`fish` shell](https://fishshell.com/). For other Unix shells like `ksh`, `bash`, `sh`, or `zsh` the behavior will the same
> refactor: Change ${PWD} with $PWD

- docs/source/how-to/developing-substra/local-deployment.rst
Small correction on the local-deployment page
> chore: correction on local deployment page

- .github/workflows/test-examples-subprocess.yml
- docs/source/examples/substrafl/get_started/run_mnist_torch.ipynb
On top of:
- https://github.com/Substra/substra-documentation/pull/388
To run the examples on a dedicated workflow
> chore: add local examples to workflow

- docs/source/additional/release.rst
- docs/source/additional/releases.yaml
- docs/source/examples/substra_core/diabetes_example/assets/functions/aggregation/Dockerfile
- docs/source/examples/substra_core/diabetes_example/assets/functions/local_first_order_computation/Dockerfile
- docs/source/examples/substra_core/diabetes_example/assets/functions/local_second_order_computation/Dockerfile
- docs/source/examples/substra_core/titanic_example/assets/function_random_forest/predict/Dockerfile
- docs/source/examples/substra_core/titanic_example/assets/function_random_forest/train/Dockerfile
- docs/source/examples/substra_core/titanic_example/assets/metric/Dockerfile
> release: 035.0

- CHANGELOG.md
- docs/source/additional/release.rst
> fix: changelogs

- .github/workflows/build.yml
- CHANGELOG.md
- docs/doc-requirements.txt
- docs/environment.yml
- docs/source/conf.py
- requirements.txt
Fixes FL-1437
Cf issue https://github.com/spatialaudio/nbsphinx/issues/776
> fix: pin nbconvert 7.13 to re-run examples 

- CHANGELOG.md
- docs/source/substrafl_doc/substrafl_overview.rst
> docs: Update python version compability

- docs/source/documentation/concepts.rst
- docs/source/examples/substra_core/diabetes_example/run_diabetes.ipynb
- docs/source/examples/substra_core/titanic_example/run_titanic.ipynb
- docs/source/how-to/using-substra/debug.rst
- docs/source/how-to/using-substra/get_performances.rst
> chore: deployed to remote renaming

- changes/412.changed
- docs/source/examples/substra_core/diabetes_example/run_diabetes.ipynb
- docs/source/examples/substra_core/titanic_example/run_titanic.ipynb
- docs/source/examples/substrafl/get_started/run_mnist_torch.ipynb
- docs/source/examples/substrafl/go_further/run_diabetes_substrafl.ipynb
- docs/source/examples/substrafl/go_further/run_iris_sklearn.ipynb
- docs/source/examples/substrafl/go_further/run_mnist_cyclic.ipynb
- https://github.com/Substra/substra/pull/405 (main)
- https://github.com/Substra/substra-documentation/pull/412
- https://github.com/Substra/substrafl/pull/202
- https://github.com/Substra/substra-backend/pull/860
- https://github.com/Substra/substra-tests/pull/337
- https://github.com/Substra/orchestrator/pull/394
> chore: remove type in dataset

- docs/source/index.rst
- docs/source/reference/index.rst
> feat: add Pod Security Standard reference

- changes/429.added
- docs/source/how-to/deploying-substra/howto/customize-compute-pod-node.rst
- docs/source/how-to/deploying-substra/index.rst
> feat: add customization compute pod node

- docs/source/conf.py
closes FL-1667
Cf https://about.readthedocs.com/blog/2024/07/addons-by-default/ for more info
> chore: use rtd sphinx addons

- docs/source/examples/substra_core/diabetes_example/assets/functions/aggregation/Dockerfile
- docs/source/examples/substra_core/diabetes_example/assets/functions/local_first_order_computation/Dockerfile
- docs/source/examples/substra_core/diabetes_example/assets/functions/local_second_order_computation/Dockerfile
- docs/source/examples/substra_core/titanic_example/assets/function_random_forest/predict/Dockerfile
- docs/source/examples/substra_core/titanic_example/assets/function_random_forest/train/Dockerfile
- docs/source/examples/substra_core/titanic_example/assets/metric/Dockerfile
- docs/source/examples/substra_core/titanic_example/run_titanic.ipynb
To change on next release, but to fix the CI in the meantime
> fix: pin substra-tools version in examples
