Substra/substra-documentation

.travis.yml, Makefile
- Makes sure the `docs/` folder contains a `/nojekyll` file
- Fixes a conflict in travis where cloning `.github.git` conflicted with the `.github/CODEOWNERS` directory.
=> Add  .nojekyll file to docs folder

docs/_sources/setup/further_resources.md.txt, docs/setup/further_resources.html, src/setup/further_resources.md
For example, in the venv section: use `<YOUR_VENV>` instead of `YOUR_VENV`
=> More readable variables

docs/source/additional/glossary.rst, docs/source/operations/backend/index.rst, docs/source/operations/orchestrator/index.rst
I did some minor fixes and added links to ArtifactHUB  to let users know they can find charts information there.
=> docs: add a link to the components helm charts

CHANGELOG.md, docs/source/documentation/get_performances.rst
Signed-off-by: Fabien Gelus <fabien.gelus@owkin.com>
Steps to reproduce:
- build the doc : `make clean html` (it will run the necessary examples)
- copy the mlflow script from `docs/source/documentation/get_performances.rst` into a new .py script in `substrafl_examples/strategies_examples/`
Error: 
`mlflow.exceptions.MlflowException: Got invalid step 1 for metric 'Accuracy_MyOrg2MSP' (value=0.2022). Step must be a valid long (64-bit integer).`
=> fix: mlflow script

docs/source/documentation/debug.rst, examples/titanic_example/plot_titanic.py, substrafl_examples/strategies_examples/plot_substrafl_fedavg.py
https://github.com/Substra/substra/pull/287
https://github.com/Substra/substrafl/pull/19
https://github.com/Substra/substra-tests/pull/210
https://github.com/Substra/substra-documentation/pull/178
=> feat: Client has now a backend_type argument instead of debug + env variable

CHANGELOG.md, docs/source/documentation/debug.rst
Companion PRs:
- https://github.com/Substra/substra-backend/pull/483 (main PR)
- https://github.com/Substra/orchestrator/pull/38
- https://github.com/Substra/substra/pull/295
- https://github.com/Substra/substra-tests/pull/218
- https://github.com/Substra/substra-frontend/pull/116
- https://github.com/Substra/substra-documentation/pull/184 (this PR)
---
=> docs: container build error logs are now accessible to end users

docs/source/conf.py, examples/titanic_example/plot_titanic.py, substrafl_examples/strategies_examples/plot_substrafl_fedavg.py
I didn't updated the changelog has this feature concerns releases 23 (and 21, 22 has not been released yet)
Companion PRs:
substra-tests: https://github.com/Substra/substra-tests/pull/219 
substrafl: https://github.com/Substra/substrafl/pull/29
substra: https://github.com/Substra/substra/pull/294 (main) 
documentation: https://github.com/Substra/substra-documentation/pull/186 (here)
orchestrator: https://github.com/Substra/orchestrator/pull/42
backend: https://github.com/Substra/substra-backend/pull/487
=> remove: algo category from schemas and models

CHANGELOG.md, docs/source/conf.py, examples/titanic_example/assets/algo_random_forest/predict/Dockerfile, examples/titanic_example/assets/algo_random_forest/titanic_algo_rf.py, examples/titanic_example/assets/algo_random_forest/train/Dockerfile, examples/titanic_example/assets/metric/Dockerfile, examples/titanic_example/assets/metric/titanic_metrics.py, substrafl_examples/strategies_examples/assets/metric/Dockerfile, substrafl_examples/strategies_examples/assets/metric/metrics.py
Companion PR:
- MAIN: https://github.com/Substra/substra-tools/pull/63
- https://github.com/Substra/substra/pull/303
- https://github.com/Substra/substrafl/pull/34
- https://github.com/Substra/substra-documentation/pull/201
- https://github.com/Substra/substra-tests/pull/224
=> feat: algo to function in substratools

CHANGELOG.md, docs/source/substrafl_doc/substrafl_overview.rst, examples/titanic_example/assets/algo_random_forest/predict/Dockerfile, examples/titanic_example/assets/algo_random_forest/train/Dockerfile, examples/titanic_example/assets/metric/Dockerfile, substrafl_examples/get_started/torch_fedavg_assets/metric/Dockerfile, substrafl_examples/go_further/sklearn_fedavg_assets/metric/Dockerfile
Update substratools Docker image to the new one using new Ubuntu LTS (22.04) and supporting Python 3.10.
- https://github.com/Substra/substra/pull/316
- https://github.com/Substra/substra-tools/pull/68
- https://github.com/Substra/substrafl/pull/49
- https://github.com/Substra/substra-tests/pull/230
=> feat: add python 3.10 support

docs/source/additional/release.rst
=> chore: update substrafl version to 0.30.2 in compatibility table

CONTRIBUTORS.md, docs/source/contributing/code-of-conduct.rst, docs/source/contributing/contributing-guide.rst, docs/source/index.rst
Signed-off-by: Milouu <milan.roustan@owkin.com>
Add a contributing guide & code of conduct to the documentation. We add these in the documentation to centralize it. We will then be able to create CONTRIBUTING.md & CODE_OF_CONDUCT.md files in the other repositories referencing these pages.
=> feat: Add contributing guide & code of conduct

docs/source/contributing/local-deployment.rst
Minor improvements for the local deployment guide. 
The first commit proposes various improvements following remarks from first-time users. 
The second commit removes the option to install the frontend directly with `npm` in favour of a deployment using `Docker`.
=> docs: minor improvements for local deployment guide

docs/source/operations/howto/backend-deployment.rst, docs/source/operations/howto/frontend-deployment.rst
Add a page with instructions on how to deploy the frontend.
I didn't restate all the instructions on Helm and so, since they are already in the backend and the orchestrator. Maybe I ought to?
Another thought: many problems encountered when deploying the frontend are routing problems, which aren't covered here (set up an ingress controller, set up a way to generate certificates). It's not our job to document this stuff but it might be helpful to people who don't know much about Kubernetes and·or trafic routing.
=> doc: how to deploy the frontend

examples/titanic_example/assets/dataset/titanic_opener.py, examples/titanic_example/assets/function_random_forest/predict/Dockerfile, examples/titanic_example/assets/function_random_forest/titanic_function_rf.py, examples/titanic_example/assets/function_random_forest/train/Dockerfile, examples/titanic_example/assets/metric/titanic_metrics.py, examples/titanic_example/assets/requirements.txt, examples/titanic_example/run_titanic.py
Unit commits for review / roll-back
=> chore: update titanic

docs/source/contributing/local-deployment/k3-create.sh
I am encountering this error:
```
INFO[0002] Starting Node 'k3d-k3s-default-server-0'     
WARN[0003] warning: encountered fatal log from node k3d-k3s-default-server-0 (retrying 0/10): ctime="2023-02-23T15:25:56Z" level=fatal msg="no-deploy flag is deprecated. Use --disable instead." 
[...]
WARN[0008] warning: encountered fatal log from node k3d-k3s-default-server-0 (retrying 9/10): ctime="2023-02-23T15:26:01Z" level=fatal msg="no-deploy flag is deprecated. Use --disable instead." 
ERRO[0008] Failed Cluster Start: Failed to start server k3d-k3s-default-server-0: Node k3d-k3s-default-server-0 failed to get ready: error waiting for log line `k3s is up and running` from node 'k3d-k3s-default-server-0': stopped returning log lines: node k3d-k3s-default-server-0 is running=true in …
```
=> chore: update k3-create.sh

docs/source/additional/releases.yaml
Some tag links for the previous releases do not point to the correct tag.
=> fix: previous releases links

docs/source/conf.py
Mock torch does not work here (as done in substrafl) for an obscure reason...
The only way found was to ignore manually all warning. Sorry for the ugly PR...
=> fix: mock torch

docs/source/documentation/api_reference.rst
=> fix(docs): remove reference to absent CLI document

docs/source/operations/howto/existing-volumes.rst, docs/source/operations/howto/external-database.rst
Add a how-to page on using an external database.
The new page is called `external-database` but maybe it should just be `external-data` since we might put the external S3 instructions on there as well (once that's done).
Companion PRs:
- https://github.com/Substra/orchestrator/pull/210
- https://github.com/Substra/substra-backend/pull/658
Fixes FL-649
=> docs: external postgres

docs/source/additional/release.rst, docs/source/operations/howto/external-database.rst, docs/source/operations/upgrade-notes.rst
I just realized (a bit late) that actually the upgrade could break existing installations in some conditions. This PR adds upgrade notes to address this.
=> docs: add upgrade notes for 0.28

CHANGELOG.md, substrafl_examples/get_started/run_mnist_torch.py
- https://github.com/Substra/substra/pull/368
- https://github.com/Substra/substrafl/pull/147
- https://github.com/Substra/substra-tests/pull/263
- https://github.com/Substra/substra-documentation/pull/327
Centralize `wait_task` and `wait_compute_plan`, and re-use the implementation added in `substra` through the other components.
Fixes FL-1052
=> chore: use `Client.wait_compute_plan`

docs/source/operations/howto/sso-oidc.rst
Adding some text in how-to to explain how the new feature flag works.
Fixes FL-989
=> feat: how to use user require approval

substrafl_examples/go_further/run_diabetes_substrafl.py, substrafl_examples/go_further/run_mnist_cyclic.py
=> fix: typo in go further examples

docs/source/operations/howto/sso-oidc.rst
The bullet points were not properly displayed.
Before:
After:
=> docs: fix typo in SSO documentation

docs/source/documentation/api_tokens_generation.rst, docs/source/documentation/client_configuration.rst
https://github.com/Substra/substra/pull/378 makes the token generation how-to into a landing page for annoyed data scientists. This PR therefore expands it a bit, so it can better solve the problem immediately without having to browse through the documentation.
=> docs: expand the token generation how-to

docs/source/how-to/using-substra/api_tokens_generation.rst
Add a note at the top of the token generation howto, explaining why you should, what you should do if you don't, and that administrators can disable it.
I'd like to add a link to the proper helm chart value in that last item, but I don't really know what to link to (the value is `server.allowImplicitLogin`.
Companion PR to https://github.com/Substra/substra-backend/pull/698
Similar to https://github.com/Substra/substra-documentation/pull/335 and https://github.com/Substra/substra/pull/378
=> docs: add a note arguing you should generate tokens

docs/source/additional/release.rst, docs/source/documentation/backend/index.rst, docs/source/documentation/components.rst, docs/source/documentation/frontend/index.rst, docs/source/documentation/orchestrator/index.rst, docs/source/how-to/deploying-substra/walkthrough/20-orchestrator-deployment.rst, docs/source/how-to/deploying-substra/walkthrough/30-backend-deployment.rst, docs/source/how-to/deploying-substra/walkthrough/40-connect-organizations.rst
I noticed https://github.com/Substra/substra-documentation/pull/348 used `orchestrator` (not capitalized) to match `backend`, which I fully agree with since "orchestrator" is a foremost a role, just like "backend"; this spreads the change to all the documentation for consistency.
=> docs: standardize capitalization

docs/source/documentation/concepts.rst, docs/source/how-to/using-substra/get_performances.rst, docs/source/how-to/using-substra/gpu.rst
Rename title to bring more harmony to the docs.
=> docs: Rename titles

CHANGELOG.md, docs/source/additional/release.rst, docs/source/additional/releases.yaml
- Add user management doc ([#345](https://github.com/Substra/substra-documentation/pull/345))
- Add link to python libraries documentation in Components page ([#347](https://github.com/Substra/substra-documentation/pull/347))
- Add more orchestrator documentation ([#346](https://github.com/Substra/substra-documentation/pull/346))
- Deactivate Binder ([#340](https://github.com/Substra/substra-documentation/pull/340))
- Reorganise documentation according to [diataxis](https://diataxis.fr/) approach ([#330](https://github.com/Substra/substra-documentation/pull/330))
- Added section about channels in the main concepts ([#344](https://github.com/Substra/substra-documentation/pull/344))
- Add frontend documentation in components section …
=> chore: release 0.31.0

CHANGELOG.md, docs/source/how-to/developing-substra/local-deployment/k3-create.sh
Propose a Skaffold profile to create 3 orgs in standalone mode.
This profile is called "three_orgs".
CI + Locally
- https://github.com/Substra/substra-backend/pull/733
- https://github.com/Substra/orchestrator/pull/280
- https://github.com/Substra/substra-documentation/pull/365
=> chore: update k3s_create.sh to allow third organization

CHANGELOG.md, docs/source/additional/release.rst, docs/source/conf.py
Hopefully closes FL-1124
`docs/source/additional/releases.yaml` → `docs/source/additional/releases.json`
For what it's worth... [build#366](https://owkin-substra-documentation--366.com.readthedocs.build/en/366/releases.json)
=> fix(docs/source/additional/release): link to json release table

CHANGELOG.md, docs/source/additional/release.rst, docs/source/additional/releases.yaml, docs/source/examples/substra_core/diabetes_example/assets/functions/aggregation/Dockerfile, docs/source/examples/substra_core/diabetes_example/assets/functions/local_first_order_computation/Dockerfile, docs/source/examples/substra_core/diabetes_example/assets/functions/local_second_order_computation/Dockerfile, docs/source/examples/substra_core/titanic_example/assets/function_random_forest/predict/Dockerfile, docs/source/examples/substra_core/titanic_example/assets/function_random_forest/train/Dockerfile, docs/source/examples/substra_core/titanic_example/assets/metric/Dockerfile, docs/source/how-to/developing-substra/local-deployment.rst
Closes FL-1227
[docs](https://owkin-substra-documentation--370.com.readthedocs.build/en/370/additional/release.html)
=> chore: release 0.33.0

CHANGELOG.md, docs/source/documentation/concepts.rst, docs/source/substrafl_doc/substrafl_overview.rst
Add some docs on the default permissions settings for FedAvg and what the user can see in the front with/without permissions.
Closes FL-1174
=> chore(docs): Add doc for task outputs permissions

docs/source/additional/release.rst
The link was using markdown syntax instead of rst.
=> fix: bad link in release

docs/source/how-to/using-substra/get_performances.rst
=> chore: add warning to local monitoring page

docs/source/how-to/developing-substra/harbor.rst, docs/source/how-to/developing-substra/index.rst, docs/source/how-to/developing-substra/local-deployment/k3-create.sh
Describe how to start a cluster with Harbor
Fixes  FL-1477 & FL-1479
- https://github.com/Substra/substra-backend/pull/862
=> feat: add profile to launch harbor as external registry

docs/source/how-to/deploying-substra/upgrade-notes.rst
=> feat: add upgrade not for warning after release 0.38

changes/425.added, docs/source/reference/index.rst, docs/source/reference/netpol.rst, docs/source/reference/pss.rst
=> feat: add network policies reference

.github/workflows/test-examples-subprocess.yml, changes/430.added, docs/source/examples/substra_core/titanic_example/assets/function_random_forest/predict/Dockerfile, docs/source/examples/substra_core/titanic_example/assets/function_random_forest/train/Dockerfile, docs/source/examples/substra_core/titanic_example/assets/metric/Dockerfile, docs/source/substrafl_doc/substrafl_overview.rst
Adding support for Python 3.12, in particular in the CI.
Dropping 3.8 and 3.9 from the CI (both versions at the same time, since we forgot to do it last time).
=> chore: support Python 3.12

changes/431.fixed, docs/source/examples/substrafl/get_started/run_mnist_torch.ipynb, docs/source/examples/substrafl/get_started/torch_fedavg_assets/requirements.txt, docs/source/examples/substrafl/go_further/run_mnist_cyclic.ipynb, docs/source/examples/substrafl/go_further/torch_cyclic_assets/requirements.txt
=> chore: bump Pytorch version to 2.2.1 in examples

CHANGELOG.md, changes/424.added, changes/425.added, changes/427.fixed, changes/429.added, changes/430.added, changes/431.fixed, changes/436.changed, docs/source/additional/release.rst, docs/source/additional/releases.yaml, docs/source/examples/substra_core/diabetes_example/assets/functions/aggregation/Dockerfile, docs/source/examples/substra_core/diabetes_example/assets/functions/local_first_order_computation/Dockerfile, docs/source/examples/substra_core/diabetes_example/assets/functions/local_second_order_computation/Dockerfile, docs/source/examples/substra_core/titanic_example/assets/function_random_forest/predict/Dockerfile, docs/source/examples/substra_core/titanic_example/assets/function_random_forest/train/Dockerfile, docs/source/examples/substra_core/titanic_example/assets/metric/Dockerfile
https://substra-documentation--438.org.readthedocs.build/en/438/additional/release.html
=> chore: release 0.39.0
